---
broker: amqp://guest:guest@localhost:5672/
result_backend: amqp
results_expire_in: 3600000
exchange: machinery_exchange
exchange_type: direct
default_queue: machinery_tasks
binding_key: machinery_key
